### PR TITLE
Add hyphen to username regex

### PR DESCRIPTION
**Pull request by Jan-PieterBaert**

### CODE REVIEW

**Comment by rien** [comment]
@redfast00 your opinion is needed whether we want to merge this.

**Comment by redfast00** [comment]
Imo, I'd rather not have this for new accounts

**Comment by Jan-PieterBaert** [comment]
Could you explain why?

**Comment by redfast00** [comment]
Sure: to avoid trouble in the future, I don't want any special characters in usernames and would like to have these "normalized" as much as possible (so for example no uppercase letters), so other software (self-written or external) doesn't do weird things with it. Granted, the current regex might lean more on the safe side (vs the expressive side), but I don't feel that users lose much expressiveness by not having those characters.

Note that existing users get to keep their username, this regex is only for new users.

**Comment by Jan-PieterBaert** [comment]
I personally feel that people with a name with a hyphen lose the expressiveness of having their name in their username, I don't see why a hyphen would be a problem in a program...

**Comment by bobbybobbypangang** [comment]
I agree with Jan-Pieter. I find only lowercase and numbers way too restrictive. You can't even combine words because there is nothing to separate them. I can't remember any system I registered that didn't even accept upper case letters, and I would find it a shame if zeus is more restrictive then anything else. If there is nothing you can list right now that will cause a problem them my vote as a bestuur goes for allowing at least upper case,hyphen and underscore in addition to the lower case and numbers.

**Comment by bobbybobbypangang** [comment]
I also don't agree that you decided and closed this issue like that...

**Comment by redfast00** [comment]
I know that uppercase will cause problems: some applications normalize to lowercase, some don't, and then you have a "different" username on those, which would complicate synchronizing between those.

**Comment by redfast00** [comment]
As for the closing, this is a technical matter, I assumed this fell under my responsibility as systems administrator to make a decision on.

**Comment by wschella** [comment]
You can also check duplication against the normalized version of the names (but still allow more flexibility).
E.g. you can't have both `jan-pieter` and `jan_pieter` or `Jan-Pieter`
You don't even have to save an extra column in the database for this, there's never going to be so many zeus members that this becomes a performance issue.

**Review by redfast00 — APPROVED** [review]

**Comment by rien** [comment]
@Jan-PieterBaert @redfast00 please check if the PR is how you'd like it.

**Comment by Jan-PieterBaert** [comment]
All good for me @rien

**Pull request merged**
